### ISSUE TITLE
Big buffers

### ISSUE THREAD

**Issue by Deleplace** [machinebox/progress#2]
Looking at the source code, I assume that the frequency of the progress update is limited by the time it takes to the underlying `ReaderOrWriter` to complete one call of `ReadOrWrite([]byte)`. 1 completed call -> at most 1 progress step.

This is fine when the buffer sizes are small compared to the total size of the stream. But the progress indicator may seem stale in case the buffers are oversize and the throughput is low.

How about an option to limit buffer sizes, in order to increase progress frequency if the caller feels she needs it?

Of course, this would complicate implementation : 

`progressReader.Read(bigBuffer)` would be a serialization of `r.Read(smallSlice1), r.Read(smallSlice2), etc.`
`progressWriter.Write(bigBuffer)` would be a serialization of `w.Write(smallSlice1), w.Write(smallSlice2), etc.`

This may also negatively impact the performance (throughput) if the buffer size limit is chosen too small.

**Comment by Deleplace** [comment]
This proposal assumes that any call to `io.Reader.Read` can be safely cut into smaller calls while remaining strictly equivalent, and the same for any call to `io.Writer.Write`.

From my understanding of the spirit of package `io`, this assumption holds true. I'd be glad to be proven wrong.

I understand that a custom implementation of `io.Reader` or `io.Writer` could start behaving differently, or even exhibit bugs, when called with buffer arguments "smaller than usual", but then I think the problem would lie within the implementation itself.

**Comment by matryer** [comment]
This is interesting. Are there any real-world examples where the buffer sizes are so big that this would seem to hang? For downloading files and reading response bodies, it works great.

**Comment by Deleplace** [comment]
I don't know of any real-world need for this!

It is more like an edge-case goodie in a lean swiss-army-knife Progress lib, "because we want progress notifications, and in theory stalling could happen".

When could it happen that either the buffers are very large, or the throughput is very low?  Hmm... spectre attack, 10KB/s. What a delight it would be to read a smooth "Attack 2.35% complete ... 2.36% ... 2.37%". Just kidding, of course.
